In [1]:
import numpy as np

Question 3

In [2]:
x1 = np.array([12, 5.5, 4.7, 15.5, 3])
x2 = np.array([6, 8.3, 4.5, 7.3, 7])
x3 = np.array([3, 5, 2, 9, 7])
y = np.array([4, 2, 5, 3, 2])

print(x1, x2, x3, y)

[12.   5.5  4.7 15.5  3. ] [6.  8.3 4.5 7.3 7. ] [3 5 2 9 7] [4 2 5 3 2]


In [3]:
x = np.vstack((x1, x2, x3, np.ones(5)))
x

array([[12. ,  5.5,  4.7, 15.5,  3. ],
       [ 6. ,  8.3,  4.5,  7.3,  7. ],
       [ 3. ,  5. ,  2. ,  9. ,  7. ],
       [ 1. ,  1. ,  1. ,  1. ,  1. ]])

In [4]:
a_d = np.array([0.1, 0.2, 0.5, 1])

In [5]:
y_pred = a_d @ x
y_pred

array([4.9 , 5.71, 3.37, 8.51, 6.2 ])

In [6]:
da = round(-np.sum(x1 * (y - y_pred)), 6)
db = round(-np.sum(x2 * (y - y_pred)), 6)
dc = round(-np.sum(x3 * (y - y_pred)), 6)
dd = round(-np.sum(y - y_pred), 6)
print(da,db,dc,dd)

121.549 98.481 96.98 12.69


In [7]:
a_d_2 = a_d - 0.1 * np.array([da, db, dc, dd])
a_d_2

array([-12.0549,  -9.6481,  -9.198 ,  -0.269 ])

In [8]:
y_pred = a_d_2 @ x
y_pred

array([-230.4104 , -192.64018, -118.73948, -340.33308, -168.3564 ])

In [9]:
da = round(-np.sum(x1 * (y - y_pred)), 6)
db = round(-np.sum(x2 * (y - y_pred)), 6)
dc = round(-np.sum(x3 * (y - y_pred)), 6)
dd = round(-np.sum(y - y_pred), 6)
print(da,db,dc,dd)

-10297.753286 -7277.629838 -6206.40358 -1066.47954


In [10]:
a_d_3 = a_d_2 - 0.1 * np.array([da, db, dc, dd])
np.round(a_d_3, 6)

array([1017.720429,  718.114884,  611.442358,  106.378954])

In [12]:
a_d = np.array([0.1, 0.2, 0.5, 1])
y_pred = a_d @ x

for i in range(3):
    da = -(x1 * (y - y_pred))[i]
    db = -(x2 * (y - y_pred))[i]
    dc = -(x3 * (y - y_pred))[i]
    dd = -(y - y_pred)[i]
    
    a_d = a_d - 0.1 * np.array([da, db, dc, dd])
    y_pred = a_d @ x
    
    print(np.round(a_d, 6))

[-0.98 -0.34  0.23  0.91]
[3.5036  6.42616 4.306   1.7252 ]
[-20.335665 -16.398668  -5.838368  -3.346984]


Question 6

In [5]:
k1 = np.array([[-1, -1, -1], [2,2,2], [-1, -1, -1]])
k2 = np.array([[-1, 2, -1], [-1, 2, -1], [-1, 2, -1]])
k3 = np.array([[-1, -1, 2], [-1, 2, -1], [2, -1, -1]])
print(k1, k2, k3)

[[-1 -1 -1]
 [ 2  2  2]
 [-1 -1 -1]] [[-1  2 -1]
 [-1  2 -1]
 [-1  2 -1]] [[-1 -1  2]
 [-1  2 -1]
 [ 2 -1 -1]]


In [15]:
i1 = np.array([[10, 10, 10 ,10 ,10], [10, 10, 10, 10, 50], [10, 10, 10, 50, 50],[10, 10, 50, 50, 50],[10, 50, 50, 50,50]])

In [16]:
i1

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 50],
       [10, 10, 10, 50, 50],
       [10, 10, 50, 50, 50],
       [10, 50, 50, 50, 50]])

In [17]:
i1 = np.vstack((np.zeros(5), i1, np.zeros(5)))
i1 = np.hstack((np.zeros((7,1)), i1, np.zeros((7,1))))

In [24]:
i1 

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., 10., 10., 10., 10., 10.,  0.],
       [ 0., 10., 10., 10., 10., 50.,  0.],
       [ 0., 10., 10., 10., 50., 50.,  0.],
       [ 0., 10., 10., 50., 50., 50.,  0.],
       [ 0., 10., 50., 50., 50., 50.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [29]:
ans = np.zeros((7,7))
for i in range(1,6):
    for j in range(1,6):
#         print(k1 @ i1[i-1:i+2, j-1:j+2])
        ans[i,j] = np.sum(k3 * i1[i-1:i+2, j-1:j+2])
ans

array([[   0.,    0.,    0.,    0.,    0.,    0.,    0.],
       [   0.,  -10.,    0.,    0.,  -40.,  -20.,    0.],
       [   0.,    0.,    0.,  -40., -120.,  120.,    0.],
       [   0.,    0.,  -40., -120.,  120.,   40.,    0.],
       [   0.,  -40., -120.,  120.,   40.,    0.,    0.],
       [   0.,  -20.,  120.,   40.,    0.,  -50.,    0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.]])

Question 5

In [2]:
### F(C, TF1)
F_CTF1 = np.array([0.55*0.2+0.85*0.8, 
                   0.45*0.2+0.15*0.8, 
                   0.25*0.2+0.45*0.8, 
                   0.75*0.2+0.55*0.8]).reshape((2,2))
F_CTF1

array([[0.79, 0.21],
       [0.41, 0.59]])

In [3]:
F_P1C = np.array([0.2*0.79*0.25+0.6*0.41*0.75,
                 0.2*0.21*0.25+0.6*0.59*0.75,
                 0.8*0.79*0.25+0.4*0.41*0.75,
                 0.8*0.21*0.25+0.4*0.59*0.75]).reshape((2,2))
F_P1C

array([[0.224, 0.276],
       [0.281, 0.219]])

In [4]:
F_EC = np.array([0.6*0.224+0.4*0.281,
                 0.6*0.276+0.4*0.219,
                 0.95*0.224+0.2*0.281,
                 0.95*0.276+0.2*0.219]).reshape((2,2))
F_EC

array([[0.2468, 0.2532],
       [0.269 , 0.306 ]])

In [5]:
ans = [0.2468*0.5+0.269*0.5, 0.2532*0.5+0.306*0.5]
ans

[0.2579, 0.27959999999999996]

In [6]:
np.round(np.array(ans)/(ans[0]+ans[1]), 6)

array([0.479814, 0.520186])