In [1]:
import numpy as np
from collections import Counter

In [19]:
a = np.arange(20).reshape((4,5))
b = np.arange(20).reshape((4,5))
b
b[0,0]

0

In [53]:
np.sum(b, axis = 1)
np.argmax(np.sum(b, axis = 1))

AxisError: axis 1 is out of bounds for array of dimension 1

In [52]:
b = b.flatten()
b
n = Counter(b)
n[0]

1

In [21]:
c = filter(lambda x: x > 0, d)
np.array(list(c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [18]:
result = filter(lambda x: x % 2 == 0, d) 
print(list(result)) 

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [26]:
def B(a):
    ans = -(a*np.log2(a) + (1-a)*np.log2(1-a))
    return ans

In [36]:
b = B(5/8)
b

0.954434002924965

In [29]:
9/14

0.6428571428571429

In [37]:
A1 = b - (0+5/8*B(2/5))
A2 = b - (4/8*B(2/4)+4/8*B(3/4))
A3 = b - (4/8*B(2/4)+4/8*B(3/4))
A4 = b - (4/8*B(3/4)+4/8*B(2/4))
print(A1,A2,A3,A4)

0.34758988139079716 0.04879494069539858 0.04879494069539858 0.04879494069539858


In [38]:
b2 = B(2/5)
A2 = b2 - (3/5*B(1/3)+2/5*B(1/2))
A3 = b2 - (3/5*B(1/3)+2/5*B(1/2))
A4 = b2 - (2/5*B(1/2)+3/5*B(1/3))
print(A2,A3,A4)

0.01997309402197489 0.01997309402197489 0.01997309402197489


In [9]:
b = np.array([3, 0,1,2,])

In [4]:
b[:0]+b[1:]

[1, 2, 3]

In [53]:
a= np.array([[1,4,7],[2,9,9],[0,5,2]])
print(a)
a[np.lexsort([a.T[0]])]

[[1 4 7]
 [2 9 9]
 [0 5 2]]


array([[0, 5, 2],
       [1, 4, 7],
       [2, 9, 9]])

In [35]:
print(a[np.lexsort([a.T[1]])])
np.roll(a[np.lexsort([a.T[1]])][:,1],-1)

[[1 4 7]
 [0 5 2]
 [2 9 9]]


array([5, 9, 4])

In [16]:
np.zeros((5))

array([0., 0., 0., 0., 0.])

In [50]:
a

array([[1, 4, 7],
       [2, 9, 9],
       [0, 5, 2]])

In [22]:
a[:,1][:-1]

array([4, 9])

In [26]:
a[:, (1,2)]

array([[4, 7],
       [9, 9],
       [5, 2]])

In [29]:
for i in range(2,10):
    print(i)

2
3
4
5
6
7
8
9


In [32]:
c = -np.inf
c>-1

False

In [23]:
arr = np.arange(10)
np.random.randint(10, size=5)


array([9, 1, 0, 1, 0])

In [56]:
np.atleast_2d(b).shape


(1, 4)

In [40]:
for index in range(0, 10):
    print(index)

0
1
2
3
4
5
6
7
8
9


In [12]:
b = np.array([6,0,0,1,2,3,4,5])
c = np.sort(np.array(list(set(b))))
print(c)
arg = list(c).index(6)
c.type

[0 1 2 3 4 5 6]


AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [18]:
1372-138

1234

In [2]:
tuple(np.int64(np.zeros(10)))

(0, 0, 0, 0, 0, 0, 0, 0, 0, 0)

In [13]:
np.log2(2)

1.0

In [3]:
tuple(np.array([1,2]))

(1, 2)

In [2]:
def addfunc(a,b,c):
    return a+b+c

In [6]:
def m(a,b,c,addfunc):
    return addfunc(c)

In [7]:
m(1,2,3, addfunc())

TypeError: addfunc() missing 3 required positional arguments: 'a', 'b', and 'c'