In [1]:
import numpy as np

In [2]:
a=np.arange(20).reshape((4,5))

In [14]:
b = a.flatten()

In [15]:
b[1]=0
b

array([ 0,  0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
b=np.arange(4)
b = b.reshape((4,1))
a*b

array([[ 0,  0,  0,  0,  0],
       [ 5,  6,  7,  8,  9],
       [20, 22, 24, 26, 28],
       [45, 48, 51, 54, 57]])

In [37]:
c=np.tile(a[0],(3,1))
c - np.array([0,1,2,3,4])

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [36]:
np.sum(c, axis=0)

array([ 0,  3,  6,  9, 12])

In [20]:
print(a)
np.diagonal(a).shape

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


(4,)

In [23]:
np.argmin(a, axis=1).shape

(4,)

In [17]:
index = np.where(b == 0)[0]
index.shape
len(index)

2

In [26]:
a
print(np.argmax(a, axis=0))
np.sum(a*a, axis=0, keepdims=True)

[3 3 3 3 3]


array([[350, 414, 486, 566, 654]])

In [6]:
np.exp(0.5)

1.6487212707001282

In [28]:
likelihood = -np.inf
likelihood

-inf

In [48]:
A = np.reshape(np.arange(24),(4,3,2))
B = np.reshape(A,(-1,2))
B.reshape(4,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [61]:
initial_means=[1,2,3,4,5]
if initial_means is None:
    print(1)
# type(initial_means)

In [40]:
end = True
while(not end):
    print(1)

In [47]:
clusters = np.zeros(5, dtype=int)
clusters

array([0, 0, 0, 0, 0])

In [62]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [63]:
a/0

d:\anaconda\envs\ai_env\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
d:\anaconda\envs\ai_env\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [21]:
prev_likelihood = 1
new_likelihood = 1
increase_convergence_ctr = (abs(prev_likelihood) * 0.9 < abs(new_likelihood) < abs(prev_likelihood) * 1.1)
increase_convergence_ctr

True

In [22]:
a,b,c=(1,2,3)
a

1

In [32]:
c

3

In [33]:
Acbd = (a, b, c)

In [34]:
Acbd

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 2,
 3)

In [8]:
import time

a = np.arange(30000).reshape((10000,3))
m,n = a.shape
b = np.arange(9).reshape((3,3))
t = time.time()
for i in range(m):
    e = np.exp(a[i, :].dot(a[i, :].T))
print(time.time()-t)
t = time.time()
print(a[0, :].dot(b),b)
print(time.time()-t)

0.03592538833618164
[15 18 21] [[0 1 2]
 [3 4 5]
 [6 7 8]]
0.0


d:\anaconda\envs\ai_env\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: overflow encountered in exp
  


In [9]:
print(a[1,:],b)
b/a[1,:]

[3 4 5] [[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0.  , 0.25, 0.4 ],
       [1.  , 1.  , 1.  ],
       [2.  , 1.75, 1.6 ]])

In [11]:
a[0, :].dot(b).dot(a[0, :].T)

60

In [18]:
a[0, :].dot(np.diagonal(b)*np.eye((3))).dot(a[0, :].T)

36.0

In [16]:
np.diagonal(b)*np.eye((3))

array([[0., 0., 0.],
       [0., 4., 0.],
       [0., 0., 8.]])

In [23]:
np.linalg.det(np.diagonal(b)*np.eye((3)))

0.0

In [11]:
93416/np.log(116966) 

8005.046549948472

In [2]:
np.log(np.e)

1.0

In [4]:
5*3+5*3*3+5

65

In [33]:
np.isclose(93416, abs(116966*np.log(5*3+5*9+5)- 273378*2), atol=100)

False

In [14]:
np.log(272949.684675788)

12.51704275196391

In [35]:
116966*np.log(5*3+5*9+4)- 273378*2

-60308.08127175266

In [19]:
(93416+12*2)/np.log(116966)

8007.1031689130905

In [18]:
3**(12)

531441

In [36]:
5*4*3/2+3*5+5-1

49.0

In [38]:
min_BIC = np.inf
min_BIC

inf

In [40]:
means = np.array([[0.34901962, 0.3647059, 0.30588236],
                          [0.9882353, 0.3254902, 0.19607843],
                          [1., 0.6117647, 0.5019608],
                          [0.37254903, 0.3882353, 0.2901961],
                          [0.3529412, 0.40784314, 1.]])

len(list(means))

5

In [43]:
for mean in list(means):
    a = np.atleast_2d(mean)

In [44]:
a.shape  < np.array([1., 0.6117647, 0.5019608])

(1, 3)

In [60]:
a = np.array([0.34901962, 0.3647059, 0.30588236])
b = np.array([0.35, 0.3654902, 0.49607843])
((a- \
     b)<0).all()

True

In [57]:
True & False & True

False